### ISSUE TITLE
请教一下lua md5之前做一次hex转换的意义是什么?

### ISSUE THREAD

**Issue by young40** [chenquanjun/Cocos2dxEncyptAndUpdate#1]
请教一下lua md5之前做一次hex转换的意义是什么?
 function hex(s)

**Comment by chenquanjun** [comment]
读出来的是文件数据，转换一下，不然长度可能获取错误。

https://github.com/dualface/v3quick/blob/592f71097fc76a1afa4cfd0f2b8f2653321a852c/quick/lib/quick-src/extra/crypto/CCCrypto.cpp#L221-L227

**Comment by young40** [comment]
感谢大佬, 我在梳理我司的祖传代码里面看到有这样的转换, 十分不解. 搜了一下, 居然找到大佬这里来了.
可能是历史中的某位前辈从大佬您这里抄来的, 又不知道经了几人手, 连quick都没用了, 这段代码还留着.

没详细看廖大的cpp里面的处理的代码, 目前我们这边求出的md5和标准md5不一致. 我改用md5.lua来算md5.

再次感谢大佬回复.
